# Repaso de DataFrames

In [1]:
import pandas as pd
import numpy as np

##### Definimos un DataFrame con dos columnas

In [2]:
data = {
    'Nombre': ['Pedro', 'María', 'Juan', 'Ana', 'Lily','Andy', 'Roberto'],
    'Edad': [25, 30, 22, 35,17,15,30],
    'Puntuación': [85, 90, 88, 78,100,25,10]
}
df = pd.DataFrame(data)

Verificamos el tipo de dato de estas dos variables creadas con `type()`

In [3]:
print('Tipo de datos de la variable data',type(data))
print('Tipo de datos de la variable df',type(df))

Tipo de datos de la variable data <class 'dict'>
Tipo de datos de la variable df <class 'pandas.core.frame.DataFrame'>

#### Imprimimos el dataframe

In [4]:
display(df) # Solo para Jupyter Notebook en Standalone usar print()
df.empty

    Nombre  Edad  Puntuación
0    Pedro    25          85
1    María    30          90
2     Juan    22          88
3      Ana    35          78
4     Lily    17         100
5     Andy    15          25
6  Roberto    30          10

False

## Podemos explorar los atributos de DataFrame
DataFrame tiene cientos de atributos y funciones que nos permiten manipular y analizar datos   \
📚[Documentación de la librería pandas.Dataframe](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html)

In [5]:
print(df.size)

21

In [6]:
print(df.empty)

False

In [7]:
print(df.count())

Nombre        7
Edad          7
Puntuación    7
dtype: int64

In [8]:
display(df.head(0))

Empty DataFrame
Columns: [Nombre, Edad, Puntuación]
Index: []

In [9]:
print(df.columns)

Index(['Nombre', 'Edad', 'Puntuación'], dtype='object')

In [10]:
df.shape

(7, 3)

In [11]:
df.describe() # Estadística descriptiva de cada columna

            Edad  Puntuación
count   7.000000    7.000000
mean   24.857143   68.000000
std     7.335498   35.378901
min    15.000000   10.000000
25%    19.500000   51.500000
50%    25.000000   85.000000
75%    30.000000   89.000000
max    35.000000  100.000000

In [12]:
len(df)

7

#### Podemos acceder a cada `Serie` dentro del `DataFrame`

In [13]:
print(df['Nombre'])
print('------   ------   ------   ------   ')
print(df['Edad'])
print('------   ------   ------   ------   ')
print(df['Puntuación'])

0      Pedro
1      María
2       Juan
3        Ana
4       Lily
5       Andy
6    Roberto
Name: Nombre, dtype: object
------   ------   ------   ------
0    25
1    30
2    22
3    35
4    17
5    15
6    30
Name: Edad, dtype: int64
------   ------   ------   ------
0     85
1     90
2     88
3     78
4    100
5     25
6     10
Name: Puntuación, dtype: int64

Para saber el tipo de dato que tenemos usamos la función `type()`

In [14]:
print(type(df['Puntuación']))

<class 'pandas.core.series.Series'>

In [15]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

### Filtrar un DataFrame
Podemos filtrar un dataframe de muchas maneras. Una función muy util es `sort_values()`\
📚[Ver documentación](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html)

Podemos ordenar los valores con la función `sort_values()` de forma ascendente o descendente

In [16]:
# Creamos una nueva variable y le asignamos el nombre df_sorted_puntos
df_sorted_puntos = df.sort_values(by='Puntuación', ascending=False)
display(df)
print('**************************************')
display(df_sorted_puntos)

    Nombre  Edad  Puntuación
0    Pedro    25          85
1    María    30          90
2     Juan    22          88
3      Ana    35          78
4     Lily    17         100
5     Andy    15          25
6  Roberto    30          10

**************************************

    Nombre  Edad  Puntuación
4     Lily    17         100
1    María    30          90
2     Juan    22          88
0    Pedro    25          85
3      Ana    35          78
5     Andy    15          25
6  Roberto    30          10

In [17]:
# Creamos una nueva variable y le asignamos el nombre df_sorted_edad
df_sorted_edad = df.sort_values(by='Edad', ascending=False)
display(df_sorted_edad)

    Nombre  Edad  Puntuación
3      Ana    35          78
1    María    30          90
6  Roberto    30          10
0    Pedro    25          85
2     Juan    22          88
4     Lily    17         100
5     Andy    15          25

### Función `iloc[]`
La función `iloc[]` se utiliza para acceder a un grupo de filas y columnas por índices\
📚[Documentación de iloc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html#pandas.DataFrame.iloc)

In [18]:
primer_valor_puntuacion = df_sorted_puntos['Puntuación'].iloc[0]
segundo_valor_puntuacion = df_sorted_puntos['Puntuación'].iloc[1]

ultimo_valor_puntuacion = df_sorted_puntos['Puntuación'].iloc[len(df_sorted_puntos)-1]
print("\nPrimer valor de la columna 'Puntuación':", primer_valor_puntuacion)
print("Segundo valor de la columna 'Puntuación':", segundo_valor_puntuacion)
print("Ultimo valor de la columna 'Puntuación':", ultimo_valor_puntuacion)

print(len(df_sorted_puntos)) # Length)

Primer valor de la columna 'Puntuación': 100
Segundo valor de la columna 'Puntuación': 90
Ultimo valor de la columna 'Puntuación': 10
7

In [19]:
primer_valor_edad = df_sorted_edad['Edad'].iloc[0]
# primer_valor_edad = df_sorted_edad['Edad'].iloc[len(df_sorted_edad)-1]
print("\nPrimer valor de la columna 'Edad':", primer_valor_edad)

Primer valor de la columna 'Edad': 35

## Crear y leer archivos `csv`
El formato `csv` es uno de los mas utilizados, como veremos mas adelante, para representar **datos tabulares**   

📚[to_csv](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html)\
📚[read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)

### Creacion de un archivo `csv` a partir del dataFrame `df`

In [20]:
df.to_csv('df_original2.csv', index=False)

### Lectura de un archivo `csv`
El siguiente código funciona para un archivo que esta en la misma carpeta que el modulo que estamos corriendo.

In [21]:
# Creamos una nueva variable:
df_from_csv = pd.read_csv('df_original2.csv')

# Lo mostramos en pantalla
display(df_from_csv)

    Nombre  Edad  Puntuación
0    Pedro    25          85
1    María    30          90
2     Juan    22          88
3      Ana    35          78
4     Lily    17         100
5     Andy    15          25
6  Roberto    30          10